<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductionCapacitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nama_produk' => 'pouch canvas', 'jenis' => 'jahit', 'jahit' => 1200, 'kemas_plastik' => 1500, 'kemas_box' => 500, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch canvas x miniso', 'jenis' => 'jahit', 'jahit' => 600, 'kemas_plastik' => 1000, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch miniso', 'jenis' => 'jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch croco', 'jenis' => 'jahit', 'jahit' => 600, 'kemas_plastik' => 1000, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch canvas x miniso Tropical Ultimate', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 700, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 1300, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch canvas resize', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 1300, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch canvas x miniso resize', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 800, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch miniso resize', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 800, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch croco resize', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 800, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada resize', 'jenis' => 'jahit', 'jahit' => 600, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch bulu kucing', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch bulu kucing resize', 'jenis' => 'jahit', 'jahit' => 600, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch vynil', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 500, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch gail', 'jenis' => 'jahit', 'jahit' => 1000, 'kemas_plastik' => 1200, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch gail renda', 'jenis' => 'jahit', 'jahit' => 600, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch blacu', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada urban basic', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada bella', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch miniso urban ultimate', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada urban fold ultimate', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch canvas fabric ultimate', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch kosmetik', 'jenis' => 'jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch prada boxy', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch gail boxy', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 400, 'kemas_box' => 350, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch gail x miniso boxy', 'jenis' => 'jahit', 'jahit' => 250, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch bulu kucing boxy', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'pouch croco boxy', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'keyholder prada', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'keyholder lipat 3', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'cardholder', 'jenis' => 'jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'cardholder curly', 'jenis' => 'jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tempat tisue', 'jenis' => 'jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tempat tisue canvas x miniso', 'jenis' => 'jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag spunbound', 'jenis' => 'jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag blacu', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas espanola', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail espanola', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas twill espanola', 'jenis' => 'jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas sofia', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag canvas liat santiago', 'jenis' => 'jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag blacu kantong', 'jenis' => 'jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail korea daegu', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas zuric', 'jenis' => 'jahit', 'jahit' => 100, 'kemas_plastik' => 300, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag prada italiano', 'jenis' => 'jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail korea', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail korea tali panjang', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag mika x twill', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail sakura', 'jenis' => 'jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag gail wina', 'jenis' => 'jahit', 'jahit' => 100, 'kemas_plastik' => 300, 'kemas_box' => 200, 'kemas_mika' => 150, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas korea', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handbag canvas korea tali panjang', 'jenis' => 'jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag blacu lipat', 'jenis' => 'jahit', 'jahit' => 400, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'totebag canvas korea ultimate', 'jenis' => 'jahit', 'jahit' => 20, 'kemas_plastik' => 150, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr kaca doff', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr sixoup', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr kaca doff slim quotes', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr kaktus rainbow', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr gradasi two colour ', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr go green', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr nice', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr rabbit dof', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr macaron', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr insert paper', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless niagara', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless sakura', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless rosewell', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless sakura led', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless japan hook', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless sport carabiner', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'tumblr stainless set vacuum', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 200, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'gelas kopi', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'gelas bar tuscany', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => 350],
            ['nama_produk' => 'mug keramik britania', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'toples kristal diamond', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 700, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 400],
            ['nama_produk' => 'gelas doff gagang', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'enamel', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 300],
            ['nama_produk' => 'enamel blirik', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 300],
            ['nama_produk' => 'enamel couple', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => 200, 'kemas_mika' => 150, 'kemas_besek' => 300, 'kemas_krongso' => null],
            ['nama_produk' => 'mangkok keramik two tone', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 150, 'kemas_besek' => 200, 'kemas_krongso' => null],
            ['nama_produk' => 'mangkok jago bening', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'mug', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'set sendok stainless leather', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'set sendok jerami', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'cermin travel gold', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handuk wajah', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'set handuk dan sanitizer', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'handsoap', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'buku yasin', 'jenis' => 'non jahit', 'jahit' => null, 'kemas_plastik' => 40, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
        ];
        DB::table('production_capacity')->insert($data);
    }
}
