<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductionCapacitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['nama_produk' => 'Pouch Canvas', 'jenis' => 'Jahit', 'jahit' => 1200, 'kemas_plastik' => 1500, 'kemas_box' => 500, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Canvas x Miniso', 'jenis' => 'Jahit', 'jahit' => 600, 'kemas_plastik' => 1000, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Miniso', 'jenis' => 'Jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Croco', 'jenis' => 'Jahit', 'jahit' => 600, 'kemas_plastik' => 1000, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Canvas x Miniso Tropical Ultimate', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 700, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 1300, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Canvas Resize', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 1300, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Canvas x Miniso Resize', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 800, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Miniso Resize', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 800, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Croco Resize', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 800, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada Resize', 'jenis' => 'Jahit', 'jahit' => 600, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Bulu Kucing', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Bulu Kucing Resize', 'jenis' => 'Jahit', 'jahit' => 600, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Vynil', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 500, 'kemas_mika' => 500, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Gail', 'jenis' => 'Jahit', 'jahit' => 1000, 'kemas_plastik' => 1200, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Gail Renda', 'jenis' => 'Jahit', 'jahit' => 600, 'kemas_plastik' => 800, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Blacu', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada Urban Basic', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada Bella', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Miniso Urban Ultimate', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada Urban Fold Ultimate', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Canvas Fabric Ultimate', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 350, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Kosmetik', 'jenis' => 'Jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Prada Boxy', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Gail Boxy', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 400, 'kemas_box' => 350, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Gail x Miniso Boxy', 'jenis' => 'Jahit', 'jahit' => 250, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Bulu Kucing Boxy', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Pouch Croco Boxy', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Keyholder Prada', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Keyholder Lipat 3', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Cardholder', 'jenis' => 'Jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Cardholder Curly', 'jenis' => 'Jahit', 'jahit' => 700, 'kemas_plastik' => 1000, 'kemas_box' => 600, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tempat Tisue', 'jenis' => 'Jahit', 'jahit' => 800, 'kemas_plastik' => 1000, 'kemas_box' => 500, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tempat Tisue Canvas x Miniso', 'jenis' => 'Jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Spunbound', 'jenis' => 'Jahit', 'jahit' => 300, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Blacu', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Espanola', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Espanola', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Twill Espanola', 'jenis' => 'Jahit', 'jahit' => 500, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Sofia', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 500, 'kemas_box' => 300, 'kemas_mika' => 250, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Canvas Liat Santiago', 'jenis' => 'Jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Blacu Kantong', 'jenis' => 'Jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Korea Daegu', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Zurich', 'jenis' => 'Jahit', 'jahit' => 100, 'kemas_plastik' => 300, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Prada Italiano', 'jenis' => 'Jahit', 'jahit' => 200, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Korea', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Korea Tali Panjang', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Mika x Twill', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Sakura', 'jenis' => 'Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Gail Wina', 'jenis' => 'Jahit', 'jahit' => 100, 'kemas_plastik' => 300, 'kemas_box' => 200, 'kemas_mika' => 150, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Korea', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handbag Canvas Korea Tali Panjang', 'jenis' => 'Jahit', 'jahit' => 50, 'kemas_plastik' => 200, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Blacu Lipat', 'jenis' => 'Jahit', 'jahit' => 400, 'kemas_plastik' => 600, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Totebag Canvas Korea Ultimate', 'jenis' => 'Jahit', 'jahit' => 20, 'kemas_plastik' => 150, 'kemas_box' => 100, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Kaca Doff', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Sixoup', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Kaca Doff Slim Quotes', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Kaktus Rainbow', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Gradasi Two Colour ', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Go Green', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Nice', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Rabbit Dof', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Macaron', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 600, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Insert Paper', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 100, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Niagara', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Sakura', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Rosewell', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Sakura LED', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Japan Hook', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Sport Carabiner', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Tumblr Stainless Set Vacuum', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 200, 'kemas_box' => 200, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Gelas Kopi', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Gelas Bar Tuscany', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 400, 'kemas_besek' => null, 'kemas_krongso' => 350],
            ['nama_produk' => 'Mug Keramik Britania', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 300, 'kemas_box' => 300, 'kemas_mika' => 200, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Toples Kristal Diamond', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 700, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 400],
            ['nama_produk' => 'Gelas Doff Gagang', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 500, 'kemas_box' => 400, 'kemas_mika' => 300, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Enamel', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 300],
            ['nama_produk' => 'Enamel Blirik', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => 300, 'kemas_besek' => 300, 'kemas_krongso' => 300],
            ['nama_produk' => 'Enamel Couple', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => 200, 'kemas_mika' => 150, 'kemas_besek' => 300, 'kemas_krongso' => null],
            ['nama_produk' => 'Mangkok Keramik Two Tone', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 400, 'kemas_box' => 300, 'kemas_mika' => 150, 'kemas_besek' => 200, 'kemas_krongso' => null],
            ['nama_produk' => 'Mangkok Jago Bening', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Mug', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Set Sendok Stainless Leather', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Set Sendok Jerami', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Cermin Travel Gold', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handuk Wajah', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Set Handuk dan Sanitizer', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => null, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Handsoap', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 600, 'kemas_box' => 500, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
            ['nama_produk' => 'Buku Yasin', 'jenis' => 'Non Jahit', 'jahit' => null, 'kemas_plastik' => 40, 'kemas_box' => null, 'kemas_mika' => null, 'kemas_besek' => null, 'kemas_krongso' => null],
        ];
        DB::table('production_capacity')->insert($data);
    }
}
